name: SE333_CI
on:
  push:
    branches:
      - main

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Build Project
        run: mvn clean compile
        working-directory: ./codebase

      - name: Run Checkstyle
        run: mvn checkstyle:check
        working-directory: ./codebase

      - name: Upload Checkstyle Result
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: |
              codebase/checkstyle-result.xml

      - name: Run Maven Test
        run: mvn test
        working-directory: ./codebase

      - name: Jacoco Report
        if: always()
        run: mvn jacoco:report
        working-directory: ./codebase

      - name: Upload Jacoco Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco
